# To disable database DAO, remove the database section. All output will then be to file, exclusively.
# To disable all output, delete both sections (why?)

configuration_file_version: 1

# Turns on console output for certain backend tasks (such as asynch commits) and statistics
debug: true

default_buffer_size: 100
default_buffer_count: 3

dao:
  database:
    driver: mysql
    host:
    port: 3306
    username:
    password:
    database: devotion
    schema:
    # Database delay is milliseconds, it's adaptive.
    debug: true
    delay: 250
    max_run: 100
  file:
#    base: Devotion/
    max_file_size: 262144000
    max_io_rate: 1048576
    io_chunk_size: 4096
    # File delay is not adaptive, it's server ticks.
    delay: 200
    debug: true
    max_run: 100

monitors:
  movement:
    sampling: onevent
    sampling_period: 1000
# List of people to monitor. Only loaded on startup or modified by /dev-w command while running.
    watch:
    - 1e4ac1d6-5ca3-4bd4-8a1e-63e82d174152
#   sampling_size: 5  (for continuous/roundrobin)
  interaction:
    sampling_delay: 5
    watch:
    - 1e4ac1d6-5ca3-4bd4-8a1e-63e82d174152
#  inventory:
#    active: true

