# To disable database DAO, set driver: none. All output will then be to file, exclusively.
# Under monitor section, any section without a buffer size and count will use the defaults.
# Don't mess with these lightly. 

configuration_file_version: 1

# Turns on console output for certain backend tasks (such as asynch commits) and statistics
debug: true

default_buffer_size: 100
default_buffer_count: 3

dao:
  database:
    driver: mysql
    host:
    port: 2306
    username:
    password:
    database: devotion
    schema:
    # Database delay is milliseconds, it's adaptive.
    delay: 250
    max_run: 100
  file:
    base: Devotion/
    max_file_size: 262144000
    max_io_rate: 1048576
    io_chunk_size: 4096
    # File delay is not adaptive, it's server ticks.
    delay: 200
    max_run: 100

monitor:
  movement:
    sampling: onevent
    sampling_period: 1000
#   sampling_size: 5  (for continuous/roundrobin)
  inventory:
    active: true
