name: ${project.name}
main: com.programmerdan.minecraft.devotion.Devotion
author: ProgrammerDan
authors: [Aleksey-Terzi]
version: ${project.version}
commands:
   devotion:
      description: Deep insight into player activity without lagging your server
      usage: To view help, use /devotion help
   devotion stats:
      description: Outputs throughput and capture statistics. Exclusively reads from internally maintained fields.
      usage: /devotion stats [monitor/handler]
      aliases: dev-s
      permission: Devotion.passive
   devotion control:
      description: Turn on or off various monitors or data handlers
      usage: /devotion control <monitor/handler> [on|off]
      aliases: dev-c
      permissions: Devotion.active
permissions:
    Devotion.*:
      description: Gives access to all Devotion commands
      default: op
      children:
        Devotion.passive: true
        Devotion.active: true
    Devotion.passive:
      description: Allows you to use any command that reads data without altering configs or performing actions 
      default: op
    Devotion.active:
      description: Allows you to use any command that sets data, alters configs, or performs actions
      default: op
      children:
        Devotion.invisible: true
    Devotion.invisible:
      description: Permission based immunity from tracking
      default: op
