name: ${project.name}
main: com.programmerdan.minecraft.devotion.Devotion
author: ProgrammerDan
authors: [Aleksey-Terzi]
version: ${project.version}
softdepend: [NameLayer]
commands:
   devotion:
      description: Deep insight into player activity without lagging your server
      usage: To view help, use /devotion help
      permission: Devotion.passive
   devotion help:
      description: Shows commands usable with devotion
      permission: Devotion.passive
   devotion stats:
      description: Outputs throughput and capture statistics. Exclusively reads from internally maintained fields.
      usage: /devotion stats [monitor/handler]
      aliases: [s]
      permission: Devotion.passive
   devotion control:
      description: Turn on or off various monitors or data handlers 
      usage: /devotion control <monitor/handler> [on|off]
      aliases: [c]
      permission: Devotion.active
   devotion config:
      description: Turn on, off, or configure various aspects of monitors or data handlers.
      usage: /devotion config <monitor/handler> <attribute> <value>
      aliases: [f]
      permission: Devotion.active
   devotion watch:
      description: Toggles tracking for specific named players. If offline, registers to begin tracking them later. If already watching, turns it off. The watch list is stored in the config for easy maintenance. Run without a player to see a list of who is being watched by what. Include explicit add / remove to skip toggle.
      usage: /devotion watch <uuid/player> [add|remove]
      aliases: [w]
      permission: Devotion.active
permissions:
    Devotion.*:
      description: Gives access to all Devotion commands
      default: op
      children:
        Devotion.passive: true
        Devotion.active: true
    Devotion.passive:
      description: Allows you to use any command that reads data without altering configs or performing actions 
      default: op
    Devotion.active:
      description: Allows you to use any command that sets data, alters configs, or performs actions
      default: op
      children:
        Devotion.invisible: true
    Devotion.invisible:
      description: Permission based immunity from tracking
      default: op
